project:
  type: website
  output-dir: docs

website:
  title: "javielio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - posts.qmd
      - publications.qmd
        

format:
  html:
    theme:
      light: minty
      dark: Superhero
    css: styles.css
    toc: true

editor: visual

